name: islamic_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  intl: ^0.20.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.16
  lottie: ^3.1.3
  fluttertoast: ^8.2.8
  go_router: ^14.6.2
  retrofit: ^4.4.1
  gap: ^3.0.1
  url_launcher: ^6.3.1
  animated_snack_bar: ^0.4.0
  dotted_line: ^3.2.3
  flutter_native_splash: ^2.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - .env

